name: parallel_37
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.5
  path_provider: ^2.0.10
  sqflite: ^2.0.2+1
  flutter_riverpod: ^1.0.4
  equatable: ^2.0.5
  dartz: ^0.10.1
  http: ^0.13.5
  cached_network_image: ^3.2.2
  expandable_bottom_sheet: ^1.1.1+1
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/icons/
    - assets/json/

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Light.ttf
        - asset: assets/fonts/Gilroy-Bold.ttf
        - asset: assets/fonts/Gilroy-Thin.ttf
        - asset: assets/fonts/Gilroy-UltraLight.ttf
        - asset: assets/fonts/Gilroy-Regular.ttf
        - asset: assets/fonts/Gilroy-SemiBold.ttf
        - asset: assets/fonts/Gilroy-ExtraBold.ttf
        - asset: assets/fonts/Gilroy-Black.ttf
        - asset: assets/fonts/Gilroy-Medium.ttf
        - asset: assets/fonts/Gilroy-Heavy.ttf
